/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_test_device_name               11
#define gattdb_device_information             14
#define gattdb_test_manufacturer_name_string  16
#define gattdb_test_model_number_string       18
#define gattdb_hardware_revision_string       20
#define gattdb_firmware_revision_string       22
#define gattdb_system_id                      24
#define gattdb_voice_audio_data               27
#define gattdb_voice_sample_rate              30
#define gattdb_voice_filter_enable            32
#define gattdb_voice_encoding_enable          34
#define gattdb_voice_transfer_status          36
#define gattdb_voice_audio_channels           39
#define gattdb_key_status                     42
#define gattdb_key_config                     45
#define gattdb_test_battery                   48
#define gattdb_test_battery_meas_time         51
#define gattdb_test_voice_record              53
#define gattdb_test_mic_use_left              55
#define gattdb_test_mic_pdm_delay             57
#define gattdb_test_led_tx                    59
#define gattdb_test_led_backlight             61
#define gattdb_test_key_force                 63
#define gattdb_test_accelerometer             65
#define gattdb_test_accelerometer_threshold   68
#define gattdb_ota                            69
#define gattdb_ota_control                    71


#endif // __GATT_DB_H
